<a href="https://colab.research.google.com/github/mpenaro/AlgorithmsUN2023I/blob/main/lab2/mpenaro_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -U fortran-magic

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.6 MB 7.5 MB/s 


In [ ]:
%load_ext fortranmagic

/usr/local/lib/python3.7/dist-packages/fortranmagic.py:147: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module since IPython 4.0.
  self._lib_dir = os.path.join(get_ipython_cache_dir(), 'fortran')


In [ ]:
!pip install -U -q PyDrive

from pydrive.drive import GoogleDrive

In [ ]:
import py_compile

In [ ]:
%matplotlib inline
%reload_ext fortranmagic


import sys; sys.path.append('..')

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))

ran_the_first_cell = True

jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00',
                             '2017-01-07 00:00:00+00:00',
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])

<center>
  <h1>The PyData Toolbox</h1>
  <h3>Scott Sanderson (Twitter: @scottbsanderson, GitHub: ssanderson)</h3>
  <h3><a href="https://github.com/ssanderson/pydata-toolbox">https://github.com/ssanderson/pydata-toolbox</a></h3>
</center>

# About Me:

<img src="https://github.com/havelazcoay/MetNumUN2022I/blob/main/images/me.jpg?raw=1" alt="Drawing" style="width: 300px;"/>

- Senior Engineer at [Quantopian](www.quantopian.com)
- Background in Mathematics and Philosophy
- **Twitter:** [@scottbsanderson](https://twitter.com/scottbsanderson)
- **GitHub:** [ssanderson](github.com/ssanderson)

## Outline

- Built-in Data Structures
- Numpy `array`
- Pandas `Series`/`DataFrame`
- Plotting and "Real-World" Analyses

# Data Structures

> Rule 5. Data dominates. If you've chosen the right data structures and organized things well, the algorithms
will almost always be self-evident. Data structures, not algorithms, are central to programming.

- *Notes on Programming in C*, by Rob Pike.

# Lists

### **My own example 1:**

In [ ]:
assert ran_the_first_cell, "Funciona!!!"

In [ ]:
l = [1, 'two', 3.0, 4, 5.0, "six"]
l

[1, 'two', 3.0, 4, 5.0, 'six']

### **My own example 2:**

In [ ]:
lista1 = [1, 'two', 3, 'four', 5.0, 6, 7.0, "eight"]
lista1

[1, 'two', 3, 'four', 5.0, 6, 7.0, 'eight']

In [ ]:
# Lists can be indexed like C-style arrays.
first = l[0]
second = l[1]
print("first:", first)
print("second:", second)

NameError: ignored

### **My own example 3:**

In [ ]:
# Lists can be indexed like C-style arrays.
cuarto = lista1[3]
quinto = lista1[4]
print("four:", cuarto)
print("five:", quinto)

four: four
five: 5.0


In [ ]:
# Negative indexing gives elements relative to the end of the list.
last = l[-1]
penultimate = l[-2]
print("last:", last)
print("second to last:", penultimate)

last: six
second to last: 5.0


### **My own example 4:**

In [ ]:
# Negative indexing gives elements relative to the end of the list.
last = lista1[-1]
penultimate = lista1[-2]
print("last:", last)
print("second to last:", penultimate)

last: eight
second to last: 7.0


In [ ]:
# Lists can also be sliced, which makes a copy of elements between
# start (inclusive) and stop (exclusive)
sublist = l[1:3]
sublist

['two', 3.0]

### **My own example 5:**

In [ ]:
# Lists can also be sliced, which makes a copy of elements between
# start (inclusive) and stop (exclusive)
sublist = lista1[3:7]
sublist

['four', 5.0, 6, 7.0]

### **My own example 6:**

In [ ]:
# l[:N] is equivalent to l[0:N].
first_three = l[:3]
first_three

[1, 'two', 3.0]

In [ ]:
# l[:N] is equivalent to l[0:N].
first_five = l[:5]
first_five

[1, 'two', 3.0, 4, 5.0]

### **My own example 7:**

In [ ]:
# l[3:] is equivalent to l[3:len(l)].
after_three = l[3:]
after_three

[4, 5.0, 'six']

In [ ]:
# l[4:] is equivalent to l[4:len(l)].
after_four = l[4:]
after_four

[5.0, 'six']

### **My own example 8:**

In [ ]:
# There's also a third parameter, "step", which gets every Nth element.
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h']
l[1:7:2]

['b', 'd', 'f']

In [ ]:
# There's also a third parameter, "step", which gets every Nth element.
lista2 = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h']
lista2[3:8:1]

['d', 'e', 'f', 'g', 'h']

### **My own example 9:**

In [ ]:
# This is a cute way to reverse a list.
l[::-1]

['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

In [ ]:
# This is a cute way to reverse a list.
lista2[::-1]

['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

### **My own example 10:**

In [ ]:
# Lists can be grown efficiently (in O(1) amortized time).
l = [1, 2, 3, 4, 5]
print("Before:", l)
l.append('six')
print("After:", l)

Before: [1, 2, 3, 4, 5]
After: [1, 2, 3, 4, 5, 'six']


In [ ]:
# Lists can be grown efficiently (in O(1) amortized time).
lista3 = [1, 2, 3, 4, 5]
print("antes:", lista3)
lista3.append('seis')
print("despues:", lista3)

antes: [1, 2, 3, 4, 5]
despues: [1, 2, 3, 4, 5, 'seis']


### **My own example 11:**

In [ ]:
# Comprehensions let us perform elementwise computations.
l = [1, 2, 3, 4, 5]
[x * 2 for x in l]

[2, 4, 6, 8, 10]

In [ ]:
lista4 = [1, 2, 3, 4, 5]
[x * 3 for x in lista4]

[3, 6, 9, 12, 15]

## Review: Python Lists

- Zero-indexed sequence of arbitrary Python values.
- Slicing syntax: `l[start:stop:step]` copies elements at regular intervals from `start` to `stop`.
- Efficient (`O(1)`) appends and removes from end.
- Comprehension syntax: `[f(x) for x in l if cond(x)]`.

# Dictionaries

### **My own example 12:**

In [ ]:
# Dictionaries are key-value mappings.
philosophers = {'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}
philosophers

{'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}

In [ ]:
philosophers2 = {'Harold': 'velazco', 'Juan': 'mesas', 'Isaac': 'silva'}
philosophers2

{'Harold': 'velazco', 'Juan': 'mesas', 'Isaac': 'silva'}

### **My own example 13:**

In [ ]:
# Like lists, dictionaries are size-mutable.
philosophers['Ludwig'] = 'Wittgenstein'
philosophers

{'David': 'Hume',
 'Immanuel': 'Kant',
 'Bertrand': 'Russell',
 'Ludwig': 'Wittgenstein'}

In [ ]:
philosophers2['gabriel'] = 'santos'
philosophers2

{'Harold': 'velazco', 'Juan': 'mesas', 'Isaac': 'silva', 'gabriel': 'santos'}

### **My own example 14:**

In [ ]:
del philosophers['David']
philosophers

NameError: ignored

In [ ]:
del philosophers2['Juan']
philosophers2

NameError: ignored

### **My own example 15:**

In [ ]:
# No slicing.
philosophers['Bertrand':'Immanuel']

TypeError: ignored

In [ ]:
# No slicing.
philosophers['Isaac':'Juan']

## Review: Python Dictionaries

- Unordered key-value mapping from (almost) arbitrary keys to arbitrary values.
- Efficient (`O(1)`) lookup, insertion, and deletion.
- No slicing (would require a notion of order).

<center><img src="https://github.com/havelazcoay/MetNumUN2022I/blob/main/images/pacino.gif?raw=1" alt="Drawing" style="width: 100%;"/></center>


### **My own example 16:**

In [ ]:
# Suppose we have some matrices...
a = [[1, 5, 9],
     [2, 6, 10],
     [3, 7, 11],
     [4, 8, 12]]

b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

In [ ]:
A = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [8, 9, 10]]

B = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9],
     [10, 11, 12]]

In [ ]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]

    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

<center><img src="https://github.com/havelazcoay/MetNumUN2022I/blob/main/images/gross.gif?raw=1" alt="Drawing" style="width: 50%;"/></center>


### **My own example 17:**

In [ ]:
def matrest(A, B):
    """rest matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]

    for i in range(rows_out):
        for j in range(cols_out):
            out[i][j] += A[i][j] - B[i][j]
    return out

In [ ]:
%%time

matmul(a, b)

### **My own example 18:**

In [ ]:
%%time

matrest(A, B)

### **My own example 19:**

In [ ]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(2, 3)
randm

In [ ]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(4, 6)
randm

### **My own example 20:**

In [ ]:
%%time
randa = random_matrix(600, 100)
randb = random_matrix(100, 600)
x = matmul(randa, randb)

In [ ]:
%%time
randa = random_matrix(600, 600)
randb = random_matrix(600, 600)
x = matrest(randa, randb)

### **My own example 21:**

In [ ]:
# Maybe that's not that bad?  Let's try a simpler case.
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

In [ ]:
def python_rest_vector(xs, ys):
    return [x - y for x, y in zip(xs, ys)]
python_rest_vector([1,2],[1,2])

### **My own example 22:**

In [ ]:
%%fortran
subroutine fortran_dot_product(xs, ys, result)
    double precision, intent(in) :: xs(:)
    double precision, intent(in) :: ys(:)
    double precision, intent(out) :: result

    result = sum(xs * ys)
end

In [ ]:
%%fortran
subroutine fortran_rest_vector(xs, ys, result)
    double precision, intent(in) :: xs(:)
    double precision, intent(in) :: ys(:)
    double precision, intent(out) :: result(:)

    result = xs-ys
end

### **My own example 23:**

In [ ]:
list_data = [float(i) for i in range(100000)]
array_data = np.array(list_data)

In [ ]:
list_data = [float(i) for i in range(200000)]
array_data = np.array(list_data)

### **My own example 24:**

In [ ]:
%%time
python_dot_product(list_data, list_data)

In [ ]:
%%time
a = python_rest_vector(list_data, list_data);

### **My own example 25:**

In [ ]:
%%time
fortran_dot_product(array_data, array_data)

In [ ]:
%%time
fortran_dot_product(array_data*50, array_data*50)


<center><img src="https://github.com/havelazcoay/MetNumUN2022I/blob/main/images/sloth.gif?raw=1" alt="Drawing" style="width: 1080px;"/></center>


## Why is the Python Version so Much Slower?

In [ ]:
# Dynamic typing.
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

### **My own example 26:**

In [ ]:
# Dynamic typing.
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([5, 10, 15, 20], [5, 10 + 0j, 15.0, 'five'])
#[type(x) for x in _]

### **My own example 27:**

In [ ]:
# Interpretation overhead.
source_code = 'a + b * c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

In [ ]:
#Interpretation overhead.
source_code = 'a*5 + b ** c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

## Why is the Python Version so Slow?
- Dynamic typing means that every single operation requires dispatching on the input type.
- Having an interpreter means that every instruction is fetched and dispatched at runtime.
- Other overheads:
  - Arbitrary-size integers.
  - Reference-counted garbage collection.

> This is the paradox that we have to work with when we're doing scientific or numerically-intensive Python. What makes Python fast for development -- this high-level, interpreted, and dynamically-typed aspect of the language -- is exactly what makes it slow for code execution.

- Jake VanderPlas, [*Losing Your Loops: Fast Numerical Computing with NumPy*](https://www.youtube.com/watch?v=EEUXKG97YRw)

# What Do We Do?

<center><img src="https://github.com/havelazcoay/MetNumUN2022I/blob/main/images/runaway.gif?raw=1" alt="Drawing" style="width: 50%;"/></center>

<center><img src="https://github.com/havelazcoay/MetNumUN2022I/blob/main/images/thisisfine.gif?raw=1" alt="Drawing" style="width: 1080px;"/></center>

- Python is slow for numerical computation because it performs dynamic dispatch on every operation we perform...

- ...but often, we just want to do the same thing over and over in a loop!

- If we don't need Python's dynamicism, we don't want to pay (much) for it.

- **Idea:** Dispatch **once per operation** instead of **once per element**.

In [ ]:
import numpy as np

data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

### **My own example 28:**

In [ ]:
import numpy as np
data1 = np.array([5, 6, 7, 8])
data1

array([5, 6, 7, 8])

### **My own example 29:**

In [ ]:
data + data

array([2, 4, 6, 8])

In [ ]:
data1 + data1*2

array([15, 18, 21, 24])

### **My own example 30:**

In [ ]:
%%time
# Naive dot product
(array_data * array_data).sum()

CPU times: user 2.18 ms, sys: 7 µs, total: 2.19 ms
Wall time: 3.58 ms


2666646666700000.0

In [ ]:
%%time
# Naive dot product
(array_data*2 * array_data*3).sum()

CPU times: user 3.38 ms, sys: 0 ns, total: 3.38 ms
Wall time: 3.43 ms


1.59998800002e+16

### **My own example 31:**

In [ ]:
%%time
# Built-in dot product.
array_data.dot(array_data)

CPU times: user 2.58 ms, sys: 850 µs, total: 3.43 ms
Wall time: 2.88 ms


2666646666700000.0

In [ ]:
%%time
# Built-in dot product.
array_data.dot(array_data*1513534)

CPU times: user 1.54 ms, sys: 70 µs, total: 1.61 ms
Wall time: 817 µs


4.0360603960371136e+21

### **My own example 32:**

In [ ]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 0 ns, sys: 816 µs, total: 816 µs
Wall time: 417 µs


2666646666700000.0

In [ ]:
%%time
fortran_dot_product(array_data*53151, array_data*64135)

CPU times: user 2.4 ms, sys: 64 µs, total: 2.47 ms
Wall time: 1.61 ms


9.090170183325931e+24

### **My own example 33:**

In [ ]:
# Numpy won't allow us to write a string into an int array.
data[0] = "foo"

ValueError: ignored

In [ ]:
# Numpy won't allow us to write a string into an int array.
data[0] = "Esto generara un error"

### **My own example 34:**

In [ ]:
# We also can't grow an array once it's created.
data.append(3)

In [ ]:
# We also can't grow an array once it's created.
data.append(5)

### **My own example 35:**

In [ ]:
# We **can** reshape an array though.
two_by_two = data.reshape(2, 2)
two_by_two

In [ ]:
# We **can** reshape an array though.
one_by_four = data.reshape(1, 4)
one_by_four

Numpy arrays are:

- Fixed-type

- Size-immutable

- Multi-dimensional

- Fast\*

\* If you use them correctly.

# What's in an Array?

### **My own example 36:**

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype='int16').reshape(2, 3)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[1 2 3]
 [4 5 6]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00'


In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60], dtype='int16').reshape(1, 6)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[10 20 30 40 50 60]]
DType: int16
Shape: (1, 6)
Strides: (12, 2)
Data: b'\n\x00\x14\x00\x1e\x00(\x002\x00<\x00'


# Core Operations

- Vectorized **ufuncs** for elementwise operations.
- Fancy indexing and masking for selection and filtering.
- Aggregations across axes.
- Broadcasting

# UFuncs

UFuncs (universal functions) are functions that operate elementwise on one or more arrays.

### **My own example 37:**

In [ ]:
data = np.arange(15).reshape(3, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
data = np.arange(30).reshape(5, 6)
data

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

### **My own example 38:**

In [ ]:
# Binary operators.
data * data

array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256, 289],
       [324, 361, 400, 441, 484, 529],
       [576, 625, 676, 729, 784, 841]])

In [ ]:
# Binary operators.
data*2 * data*2

array([[   0,    4,   16,   36,   64,  100],
       [ 144,  196,  256,  324,  400,  484],
       [ 576,  676,  784,  900, 1024, 1156],
       [1296, 1444, 1600, 1764, 1936, 2116],
       [2304, 2500, 2704, 2916, 3136, 3364]])

### **My own example 39:**

In [ ]:
# Unary functions.
np.sqrt(data)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
        3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
        4.12310563],
       [4.24264069, 4.35889894, 4.47213595, 4.58257569, 4.69041576,
        4.79583152],
       [4.89897949, 5.        , 5.09901951, 5.19615242, 5.29150262,
        5.38516481]])

In [ ]:
# Unary functions.
np.sqrt(data+data)

array([[0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
        3.16227766],
       [3.46410162, 3.74165739, 4.        , 4.24264069, 4.47213595,
        4.69041576],
       [4.89897949, 5.09901951, 5.29150262, 5.47722558, 5.65685425,
        5.83095189],
       [6.        , 6.164414  , 6.32455532, 6.4807407 , 6.63324958,
        6.78232998],
       [6.92820323, 7.07106781, 7.21110255, 7.34846923, 7.48331477,
        7.61577311]])

### **My own example 40:**

In [ ]:
# Comparison operations
(data % 3) == 0

array([[ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False]])

In [ ]:
# Comparison operations
(data % 2) == 0

array([[ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False]])

### **My own example 41:**

In [ ]:
# Boolean combinators.
((data % 2) == 0) & ((data % 3) == 0)

array([[ True, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [ True, False, False, False, False, False]])

In [ ]:
# Boolean combinators.
((data*3 % 2) == 0) & ((data*2 % 3) == 0)

array([[ True, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [ True, False, False, False, False, False]])

### **My own example 42:**

In [ ]:
# as of python 3.5, @ is matrix-multiply
data @ data.T

array([[  55,  145,  235,  325,  415],
       [ 145,  451,  757, 1063, 1369],
       [ 235,  757, 1279, 1801, 2323],
       [ 325, 1063, 1801, 2539, 3277],
       [ 415, 1369, 2323, 3277, 4231]])

In [ ]:
# as of python 3.5, @ is matrix-multiply
data*5 @ data.T

array([[  275,   725,  1175,  1625,  2075],
       [  725,  2255,  3785,  5315,  6845],
       [ 1175,  3785,  6395,  9005, 11615],
       [ 1625,  5315,  9005, 12695, 16385],
       [ 2075,  6845, 11615, 16385, 21155]])

# UFuncs Review

- UFuncs provide efficient elementwise operations applied across one or more arrays.
- Arithmetic Operators (`+`, `*`, `/`)
- Comparisons (`==`, `>`, `!=`)
- Boolean Operators (`&`, `|`, `^`)
- Trigonometric Functions (`sin`, `cos`)
- Transcendental Functions (`exp`, `log`)

# Selections

We often want to perform an operation on just a subset of our data.

### **My own example 43:**

In [ ]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.14, 10))
sines

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [ ]:
import math
sines = np.sin(np.linspace(0, math.pi, 10))
cosines = np.cos(np.linspace(0, math.pi, 10))
sines

array([0.00000000e+00, 3.42020143e-01, 6.42787610e-01, 8.66025404e-01,
       9.84807753e-01, 9.84807753e-01, 8.66025404e-01, 6.42787610e-01,
       3.42020143e-01, 1.22464680e-16])

### **My own example 44:**

In [ ]:
# Slicing works with the same semantics as Python lists.
sines[0]

0.0

In [ ]:
# Slicing works with the same semantics as Python lists.
sines[2]

0.6427876096865393

### **My own example 45:**

In [ ]:
sines[:3]  # First three elements

array([0.        , 0.34202014, 0.64278761])

In [ ]:
sines[:6]  # First six elements

array([0.        , 0.34202014, 0.64278761, 0.8660254 , 0.98480775,
       0.98480775])

### **My own example 46:**

In [ ]:
sines[5:]  # Elements from 5 on.

array([9.84807753e-01, 8.66025404e-01, 6.42787610e-01, 3.42020143e-01,
       1.22464680e-16])

In [ ]:
sines[3:]  # Elements from 3 on.

array([8.66025404e-01, 9.84807753e-01, 9.84807753e-01, 8.66025404e-01,
       6.42787610e-01, 3.42020143e-01, 1.22464680e-16])

### **My own example 47:**

In [ ]:
sines[::2]  # Every other element.

array([0.        , 0.64278761, 0.98480775, 0.8660254 , 0.34202014])

In [ ]:
sines[::5]  # Every other element.

array([0.        , 0.98480775])

### **My own example 48:**

In [ ]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.5)
print("sines[sines > 0.5]:\n", sines[sines > 0.5])

sines:
 [0.00000000e+00 3.42020143e-01 6.42787610e-01 8.66025404e-01
 9.84807753e-01 9.84807753e-01 8.66025404e-01 6.42787610e-01
 3.42020143e-01 1.22464680e-16]
sines > 0.5:
 [False False  True  True  True  True  True  True False False]
sines[sines > 0.5]:
 [0.64278761 0.8660254  0.98480775 0.98480775 0.8660254  0.64278761]


In [ ]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 2:\n", sines > 2)
print("sines[sines > 2]:\n", sines[sines > 2])

sines:
 [0.00000000e+00 3.42020143e-01 6.42787610e-01 8.66025404e-01
 9.84807753e-01 9.84807753e-01 8.66025404e-01 6.42787610e-01
 3.42020143e-01 1.22464680e-16]
sines > 2:
 [False False False False False False False False False False]
sines[sines > 2]:
 []


### **My own example 49:**

In [ ]:
# We index with lists/arrays of integers to select values at those indices.
print(sines)
sines[[0, 4, 7]]

[0.00000000e+00 3.42020143e-01 6.42787610e-01 8.66025404e-01
 9.84807753e-01 9.84807753e-01 8.66025404e-01 6.42787610e-01
 3.42020143e-01 1.22464680e-16]


array([0.        , 0.98480775, 0.64278761])

In [ ]:
# We index with lists/arrays of integers to select values at those indices.
print(sines)
sines[[1, 3, 6]]

[0.00000000e+00 3.42020143e-01 6.42787610e-01 8.66025404e-01
 9.84807753e-01 9.84807753e-01 8.66025404e-01 6.42787610e-01
 3.42020143e-01 1.22464680e-16]


array([0.34202014, 0.8660254 , 0.8660254 ])

### **My own example 50:**

In [ ]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data = np.array([1, 3, 2, 12, -1, 5, 2])

In [ ]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data1 = np.array([2, 5, 4, 10, -2, 6, 7])

### **My own example 51:**

In [ ]:
sort_indices = np.argsort(unsorted_data)
sort_indices

array([4, 0, 2, 6, 1, 5, 3])

In [ ]:
sort_indices1 = np.argsort(unsorted_data1)
sort_indices1

array([4, 0, 2, 1, 5, 6, 3])

### **My own example 52:**

In [ ]:
unsorted_data[sort_indices]

array([-1,  1,  2,  2,  3,  5, 12])

In [ ]:
unsorted_data1[sort_indices1]

array([-2,  2,  4,  5,  6,  7, 10])

### **My own example 53:**

In [ ]:
market_caps = np.array([12, 6, 10, 5, 6])  # Presumably in dollars?
assets = np.array(['A', 'B', 'C', 'D', 'E'])

In [ ]:
market_caps1 = np.array([10, 3, 15, 7, 2])  # Presumably in dollars?
assets = np.array(['A', 'B', 'C', 'D', 'E'])

### **My own example 54:**

In [ ]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap = np.argsort(market_caps)
assets[sort_by_mcap]

array(['D', 'B', 'E', 'C', 'A'], dtype='<U1')

In [ ]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap = np.argsort(market_caps1)
assets[sort_by_mcap]

array(['E', 'B', 'D', 'A', 'C'], dtype='<U1')

### **My own example 55:**

In [ ]:
# Indexers are also useful for aligning data.
print("Dates:\n", repr(event_dates))
print("Values:\n", repr(event_values))
print("Calendar:\n", repr(calendar))

Dates:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Values:
 array([10, 15, 20])
Calendar:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


In [ ]:
# Indexers are also useful for aligning data.
print("Fechas:\n", repr(event_dates))
print("Valores:\n", repr(event_values*5))
print("Calendario:\n", repr(calendar))

Fechas:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Valores:
 array([ 50,  75, 100])
Calendario:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


### **My own example 56:**

In [ ]:
print("Raw Dates:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Forward-Filled Dates:", calendar[calendar.searchsorted(event_dates)])

Raw Dates: ['2017-01-06' '2017-01-07' '2017-01-08']
Indices: [3 4 4]
Forward-Filled Dates: ['2017-01-06' '2017-01-09' '2017-01-09']


On multi-dimensional arrays, we can slice along each axis independently.

In [ ]:
print("fechas sin procesar:", event_dates+2)
print("Indices:", calendar.searchsorted(event_dates+5))
print("Fechas Reenviadas:", calendar[calendar.searchsorted(event_dates)])

fechas sin procesar: ['2017-01-08' '2017-01-09' '2017-01-10']
Indices: [6 7 8]
Fechas Reenviadas: ['2017-01-06' '2017-01-09' '2017-01-09']


### **My own example 57:**

In [ ]:
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
data = np.arange(30).reshape(5, 6)
data

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

### **My own example 58:**

In [ ]:
data[:2, :2]  # First two rows and first two columns.

array([[0, 1],
       [6, 7]])

In [ ]:
data[:4, :4]

array([[ 0,  1,  2,  3],
       [ 6,  7,  8,  9],
       [12, 13, 14, 15],
       [18, 19, 20, 21]])

### **My own example 59:**

In [ ]:
data[:2, [0, -1]]  # First two rows, first and last columns.

array([[ 0,  5],
       [ 6, 11]])

In [ ]:
data[:2, [2, -3]]

array([[2, 3],
       [8, 9]])

### **My own example 60:**

In [ ]:
data[(data[:, 0] % 2) == 0]  # Rows where the first column is divisible by two.

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
data[(data[:, 0] % 3) == 0]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

# Selections Review

- Indexing with an integer removes a dimension.
- Slicing operations work on Numpy arrays the same way they do on lists.
- Indexing with a boolean array filters to True locations.
- Indexing with an integer array selects indices along an axis.
- Multidimensional arrays can apply selections independently along different axes.

## Reductions

Functions that reduce an array to a scalar.

$Var(X) = \frac{1}{N}\sqrt{\sum_{i=1}^N (x_i - \bar{x})^2}$

In [ ]:
def variance(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

### **My own example 61:**

In [ ]:
variance(np.random.standard_normal(1000))

1.00639306682589

- `sum()` and `mean()` are both **reductions**.

- In the simplest case, we use these to reduce an entire array into a single value...

In [ ]:
variance(np.random.standard_normal(5000))

0.9949557288304833

### **My own example 62:**

In [ ]:
data = np.arange(30)
data.mean()

14.5

- ...but we can do more interesting things with multi-dimensional arrays.

In [ ]:
data = np.arange(50)
data.mean()

24.5

### **My own example 63:**

In [ ]:
data = np.arange(30).reshape(3, 10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
data = np.arange(50).reshape(5, 10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

### **My own example 64:**

In [ ]:
data.mean()

24.5

In [ ]:
data.mean()

24.5

### **My own example 65:**

In [ ]:
data.mean(axis=0)

array([20., 21., 22., 23., 24., 25., 26., 27., 28., 29.])

In [ ]:
data.mean(axis=0)

array([20., 21., 22., 23., 24., 25., 26., 27., 28., 29.])

### **My own example 66:**

In [ ]:
data.mean(axis=1)

array([ 4.5, 14.5, 24.5, 34.5, 44.5])

In [ ]:
data.mean(axis=1)

array([ 4.5, 14.5, 24.5, 34.5, 44.5])

## Reductions Review

- Reductions allow us to perform efficient aggregations over arrays.
- We can do aggregations over a single axis to collapse a single dimension.
- Many built-in reductions (`mean`, `sum`, `min`, `max`, `median`, ...).

# Broadcasting

### **My own example 67:**

In [ ]:
row = np.array([1, 2, 3, 4])
column = np.array([[1], [2], [3]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[1 2 3 4]
Column:
[[1]
 [2]
 [3]]


In [ ]:
row = np.array([1, 2, 3, 4, 5, 6, 7])
column = np.array([[1], [2], [3], [4]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[1 2 3 4 5 6 7]
Column:
[[1]
 [2]
 [3]
 [4]]


### **My own example 68:**

In [ ]:
row + column

array([[ 2,  3,  4,  5,  6,  7,  8],
       [ 3,  4,  5,  6,  7,  8,  9],
       [ 4,  5,  6,  7,  8,  9, 10],
       [ 5,  6,  7,  8,  9, 10, 11]])

In [ ]:
row + column

array([[ 2,  3,  4,  5,  6,  7,  8],
       [ 3,  4,  5,  6,  7,  8,  9],
       [ 4,  5,  6,  7,  8,  9, 10],
       [ 5,  6,  7,  8,  9, 10, 11]])

<center><img src="https://github.com/havelazcoay/MetNumUN2022I/blob/main/images/broadcasting.png?raw=1" alt="Drawing" style="width: 60%;"/></center>

<h5>Source: http://www.scipy-lectures.org/_images/numpy_broadcasting.png</h5>

### **My own example 69:**

In [ ]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data, sep='')
print("Mean:\n", data.mean(axis=0), sep='')
print("Data - Mean:\n", data - data.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
Mean:
[20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
Data - Mean:
[[-20. -20. -20. -20. -20. -20. -20. -20. -20. -20.]
 [-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]
 [ 20.  20.  20.  20.  20.  20.  20.  20.  20.  20.]]


In [ ]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data, sep='')
print("Mean:\n", data.mean(axis=0), sep='')
print("Data - Mean:\n", data - data.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
Mean:
[20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
Data - Mean:
[[-20. -20. -20. -20. -20. -20. -20. -20. -20. -20.]
 [-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]
 [ 20.  20.  20.  20.  20.  20.  20.  20.  20.  20.]]


# Broadcasting Review

- Numpy operations can work on arrays of different dimensions as long as the arrays' shapes are still "compatible".
- Broadcasting works by "tiling" the smaller array along the missing dimension.
- The result of a broadcasted operation is always at least as large in each dimension as the largest array in that dimension.

# Numpy Review

- Numerical algorithms are slow in pure Python because the overhead dynamic dispatch dominates our runtime.

- Numpy solves this problem by:
  1. Imposing additional restrictions on the contents of arrays.
  2. Moving the inner loops of our algorithms into compiled C code.

- Using Numpy effectively often requires reworking an algorithms to use vectorized operations instead of for-loops, but the resulting operations are usually simpler, clearer, and faster than the pure Python equivalent.

<center><img src="https://github.com/havelazcoay/MetNumUN2022I/blob/main/images/unicorn.jpg?raw=1" alt="Drawing" style="width: 75%;"/></center>

Numpy is great for many things, but...

- Sometimes our data is equipped with a natural set of **labels**:
  - Dates/Times
  - Stock Tickers
  - Field Names (e.g. Open/High/Low/Close)

- Sometimes we have **more than one type of data** that we want to keep grouped together.
  - Tables with a mix of real-valued and categorical data.

- Sometimes we have **missing** data, which we need to ignore, fill, or otherwise work around.

<center><img src="https://github.com/havelazcoay/MetNumUN2022I/blob/main/images/panda-wrangling.gif?raw=1" alt="Drawing" style="width: 75%;"/></center>

<center><img src="https://github.com/havelazcoay/MetNumUN2022I/blob/main/images/pandas_logo.png?raw=1" alt="Drawing" style="width: 75%;"/></center>


Pandas extends Numpy with more complex data structures:

- `Series`: 1-dimensional, homogenously-typed, labelled array.
- `DataFrame`: 2-dimensional, semi-homogenous, labelled table.

Pandas also provides many utilities for:
- Input/Output
- Data Cleaning
- Rolling Algorithms
- Plotting

# Selection in Pandas

### **My own example 70:**

In [ ]:
s = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[1, 2, 3, 4, 5])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
s1 = pd.Series(index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'], data=[1, 2, 3, 4, 5, 6, 7, 8])
s1

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
dtype: int64

### **My own example 71:**

In [ ]:
# There are two pieces to a Series: the index and the values.
print("The index is:", s.index)
print("The values are:", s.values)

The index is: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
The values are: [1 2 3 4 5]


In [ ]:
# There are two pieces to a Series: the index and the values.
print("El indice es:", s1.index)
print("El valor es:", s1.values)

El indice es: Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'], dtype='object')
El valor es: [1 2 3 4 5 6 7 8]


### **My own example 72:**

In [ ]:
# We can look up values out of a Series by position...
s.iloc[0]

1

In [ ]:
# We can look up values out of a Series by position...
s1.iloc[3]

4

### **My own example 73:**

In [ ]:
# ... or by label.
s.loc['a']

1

In [ ]:
# ... or by label.
s1.loc['f']

6

### **My own example 74:**

In [ ]:
# Slicing works as expected...
s.iloc[:2]

a    1
b    2
dtype: int64

In [ ]:
# Slicing works as expected...
s1.iloc[:4]

a    1
b    2
c    3
d    4
dtype: int64

### **My own example 75:**

In [ ]:
# ...but it works with labels too!
s.loc[:'c']

a    1
b    2
c    3
dtype: int64

In [ ]:
# ...but it works with labels too!
s1.loc[:'e']

a    1
b    2
c    3
d    4
e    5
dtype: int64

### **My own example 76:**

In [ ]:
# Fancy indexing works the same as in numpy.
s.iloc[[0, -1]]

a    1
e    5
dtype: int64

In [ ]:
# Fancy indexing works the same as in numpy.
s1.iloc[[0, -3]]

a    1
f    6
dtype: int64

### **My own example 77:**

In [ ]:
# As does boolean masking.
s.loc[s > 2]

c    3
d    4
e    5
dtype: int64

In [ ]:
# As does boolean masking.
s1.loc[s1 > 4]

e    5
f    6
g    7
h    8
dtype: int64

### **My own example 78:**

In [ ]:
# Element-wise operations are aligned by index.
other_s = pd.Series({'a': 10.0, 'c': 20.0, 'd': 30.0, 'z': 40.0})
other_s

a    10.0
c    20.0
d    30.0
z    40.0
dtype: float64

In [ ]:
# Element-wise operations are aligned by index.
other_s1 = pd.Series({'x': 1.0, 'y': 2.0, 'z': 3.0, 'A': 4.0})
other_s1

x    1.0
y    2.0
z    3.0
A    4.0
dtype: float64

### **My own example 79:**

In [ ]:
s + other_s

a    11.0
b     NaN
c    23.0
d    34.0
e     NaN
z     NaN
dtype: float64

In [ ]:
s1 + other_s1

A   NaN
a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
f   NaN
g   NaN
h   NaN
x   NaN
y   NaN
z   NaN
dtype: float64

### **My own example 80:**

In [ ]:
# We can fill in missing values with fillna().
(s + other_s).fillna(0.0)

a    11.0
b     0.0
c    23.0
d    34.0
e     0.0
z     0.0
dtype: float64

In [ ]:
# We can fill in missing values with fillna().
(s1 + other_s1).fillna(0.0)

A    0.0
a    0.0
b    0.0
c    0.0
d    0.0
e    0.0
f    0.0
g    0.0
h    0.0
x    0.0
y    0.0
z    0.0
dtype: float64

### **My own example 81:**

In [ ]:

# Most real datasets are read in from an external file format.
aapl = pd.read_csv('AAPL.csv', parse_dates=['Date'], index_col='Date')
aapl.head()

FileNotFoundError: ignored

In [ ]:
# Slicing generalizes to two dimensions as you'd expect:
aapl.iloc[:2, :2]

In [ ]:
# Slicing generalizes to two dimensions as you'd expect:
aapl.iloc[:3, :3]

### **My own example 82:**

In [ ]:
aapl.loc[pd.Timestamp('2010-02-01'):pd.Timestamp('2010-02-04'), ['Close', 'Volume']]

NameError: ignored

In [ ]:
aapl.loc[pd.Timestamp('2010-01-01'):pd.Timestamp('2010-04-04'), ['Close', 'Volume']]

NameError: ignored

# Rolling Operations

<center><img src="https://github.com/havelazcoay/MetNumUN2022I/blob/main/images/rolling.gif?raw=1" alt="Drawing" style="width: 75%;"/></center>

### **My own example 83:**

In [ ]:
aapl.rolling(10)[['Close', 'Adj Close']].mean().plot();

NameError: ignored

### **My own example 84:**

In [ ]:
# Drop `Volume`, since it's way bigger than everything else.
aapl.drop('Volume', axis=1).resample('3W').max().plot();

NameError: ignored

### **My own example 85:**

In [ ]:
# 30-day rolling exponentially-weighted stddev of returns.
aapl['Close'].pct_change().ewm(span=50).std().plot();

NameError: ignored

# "Real World" Data

In [ ]:
from avocados import read_avocadata

avocados = read_avocadata('2014', '2016')
avocados.head()

ModuleNotFoundError: ignored

In [ ]:
# Unlike numpy arrays, pandas DataFrames can have a different dtype for each column.
avocados.dtypes

NameError: ignored

In [ ]:
# What's the regional average price of a HASS avocado every day?
hass = avocados[avocados.Variety == 'HASS']
hass.groupby(['Date', 'Region'])['Weighted Avg Price'].mean().unstack().ffill().plot();

In [ ]:
def _organic_spread(group):

    if len(group.columns) != 2:
        return pd.Series(index=group.index, data=0.0)

    is_organic = group.columns.get_level_values('Organic').values.astype(bool)
    organics = group.loc[:, is_organic].squeeze()
    non_organics = group.loc[:, ~is_organic].squeeze()
    diff = organics - non_organics
    return diff

def organic_spread_by_region(df):
    """What's the difference between the price of an organic
    and non-organic avocado within each region?
    """
    return (
        df
        .set_index(['Date', 'Region', 'Organic'])
         ['Weighted Avg Price']
        .unstack(level=['Region', 'Organic'])
        .ffill()
        .groupby(level='Region', axis=1)
        .apply(_organic_spread)
    )

In [ ]:
organic_spread_by_region(hass).plot();
plt.gca().set_title("Daily Regional Organic Spread");
plt.legend(bbox_to_anchor=(1, 1));

In [ ]:
spread_correlation = organic_spread_by_region(hass).corr()
spread_correlation

In [ ]:
import seaborn as sns
grid = sns.clustermap(spread_correlation, annot=True)
fig = grid.fig
axes = fig.axes
ax = axes[2]
ax.set_xticklabels(ax.get_xticklabels(), rotation=45);

# Pandas Review

- Pandas extends numpy with more complex datastructures and algorithms.
- If you understand numpy, you understand 90% of pandas.
- `groupby`, `set_index`, and `unstack` are powerful tools for working with categorical data.
- Avocado prices are surprisingly interesting :)

# Thanks!